--- #YAML:1.0
name:                WebService-Simple
version:             0.02
abstract:            Simple interface to Web Services APIs
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    HTTP::Response:                0
    LWP::UserAgent:                0
    Test::More:                    0
    URI::Escape:                   0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Yusuke Wada <yusuke@kamawada.com>
